import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from '../server.mjs';
async function fixture(t,options={}) {const server=createServer(options);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));return `http://127.0.0.1:${server.address().port}`;}
const input={provider:'openai',system:'Edit this',messages:[{role:'user',content:'Text'}],max_tokens:900};
const post=(url,body=input,headers={})=>fetch(url+'/api/review',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
test('configuration reports readiness without exposing secrets; static routes do not expose env',async t=>{const url=await fixture(t,{env:{OPENAI_API_KEY:'secret',OPENAI_MODEL:'test'}});const r=await fetch(url+'/api/config');assert.deepEqual(await r.json(),{providers:{openai:true,anthropic:false}});assert.equal((await fetch(url+'/.env')).status,404);});
test('OpenAI mapping preserves instructions and returns common response format',async t=>{const url=await fixture(t,{env:{OPENAI_API_KEY:'secret',OPENAI_MODEL:'test'},fetchImpl:async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');const body=JSON.parse(options.body);assert.equal(body.store,false);assert.equal(body.instructions,input.system);assert.deepEqual(body.input,input.messages);assert.equal(options.headers.Authorization,'Bearer secret');return Response.json({output:[{type:'reasoning'},{content:[{type:'output_text',text:'[]'}]}]});}});const r=await post(url);assert.equal(r.status,200);assert.deepEqual(await r.json(),{content:[{type:'text',text:'[]'}]});});
test('Claude uses its own headers and model',async t=>{const url=await fixture(t,{env:{ANTHROPIC_API_KEY:'secret'},fetchImpl:async(url,options)=>{assert.equal(url,'https://api.anthropic.com/v1/messages');assert.equal(options.headers['x-api-key'],'secret');assert.equal(JSON.parse(options.body).model,'claude-sonnet-4-6');return Response.json({content:[{type:'text',text:'[]'}]});}});assert.equal((await post(url,{...input,provider:'anthropic'})).status,200);});
test('rejects cross-origin, invalid inputs, missing credentials and oversized requests',async t=>{const url=await fixture(t,{env:{}});assert.equal((await post(url,input,{Origin:'https://evil.example'})).status,403);assert.equal((await post(url,{...input,provider:'__proto__'})).status,400);assert.equal((await post(url,null)).status,400);assert.equal((await post(url)).status,503);assert.equal((await post(url,{...input,system:'x'.repeat(260000)})).status,413);});
test('reports truncation and upstream failure without disclosing upstream body',async t=>{let truncated=true;const url=await fixture(t,{env:{OPENAI_API_KEY:'secret',OPENAI_MODEL:'test'},fetchImpl:async()=>truncated?Response.json({status:'incomplete'}):new Response('secret',{status:401})});assert.equal((await post(url)).status,422);truncated=false;const r=await post(url);assert.equal(r.status,502);assert.ok(!(await r.text()).includes('secret'));});
