import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {createServer} from './server.mjs';
import {mkdir} from 'node:fs/promises';
import JSZip from 'jszip';
const server=createServer({env:{}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
console.log('Launching browser');
const browser=await chromium.launch({...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{channel:'chrome'}),headless:true,timeout:20000});
const page=await browser.newPage({viewport:{width:1365,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 console.log('Opening page');await page.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'domcontentloaded',timeout:20000});await page.getByLabel('Language',{exact:true}).waitFor();
 assert.equal(await page.locator('#provider option').count(),4);
 await page.getByRole('button',{name:'Options',exact:true}).click();
 assert(!/[\u0600-\u06ff]/.test(await page.locator('body').innerText()),'English UI contains Arabic');
 await page.getByLabel('Draft to review').fill('A sample passage for review.');
 await page.locator('#language').selectOption('ar');
 assert.equal(await page.locator('html').getAttribute('dir'),'rtl');
 assert.equal(await page.getByLabel('النص للمراجعة').inputValue(),'A sample passage for review.');
 await page.getByRole('button',{name:'الإعدادات',exact:true}).click();
 assert(!/Options|Review with|Forget everything|Language|Español/.test(await page.locator('body').innerText()));
 await page.locator('#provider').selectOption('manual-claude');
 await page.getByRole('button',{name:'راجع المسودة',exact:true}).click();
 await page.locator('dialog[open]').waitFor();assert.equal(await page.locator('dialog a').getAttribute('href'),'https://claude.ai/');
 await page.locator('#manual-reply').fill('invalid');await page.getByRole('button',{name:'استيراد الرد',exact:true}).click();await page.getByRole('alert').waitFor();
 await page.locator('#manual-reply').fill('[]');await page.getByRole('button',{name:'استيراد الرد',exact:true}).click();await page.waitForTimeout(300);
 await page.locator('#language').selectOption('en');
 await page.locator('input[type=file]').setInputFiles({name:'test.txt',mimeType:'text/plain',buffer:Buffer.from('Imported text.')});
 await page.getByText('test.txt',{exact:true}).waitFor();assert((await page.getByLabel('Draft to review').inputValue()).includes('Imported text.'));
 const zip=new JSZip();zip.file('[Content_Types].xml','<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');zip.file('word/document.xml','<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Document import works.</w:t></w:r></w:p></w:body></w:document>');
 await page.locator('input[type=file]').setInputFiles({name:'sample.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',buffer:await zip.generateAsync({type:'nodebuffer'})});await page.getByText('sample.docx',{exact:true}).waitFor();assert((await page.getByLabel('Draft to review').inputValue()).includes('Document import works.'));
 const stream='BT /F1 12 Tf 50 750 Td (PDF import works.) Tj ET';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];let pdf='%PDF-1.4\n',offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;}const xref=pdf.length;pdf+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
 await page.locator('input[type=file]').setInputFiles({name:'sample.pdf',mimeType:'application/pdf',buffer:Buffer.from(pdf)});await page.getByText('sample.pdf',{exact:true}).waitFor();assert((await page.getByLabel('Draft to review').inputValue()).includes('PDF import works.'));
 await page.locator('.file-zone').evaluate(node=>{const data=new DataTransfer();data.items.add(new File(['Dropped text.'],'drop.txt',{type:'text/plain'}));node.dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:data}));});await page.getByText('drop.txt',{exact:true}).waitFor();assert((await page.getByLabel('Draft to review').inputValue()).includes('Dropped text.'));
 await page.locator('input[type=file]').setInputFiles({name:'bad.doc',mimeType:'application/msword',buffer:Buffer.from('bad')});await page.getByRole('alert').waitFor();
 await mkdir('../qa',{recursive:true});await page.screenshot({path:'../qa/english.png',fullPage:true});
 await page.locator('#language').selectOption('ar');await page.screenshot({path:'../qa/arabic.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile overflow');await page.screenshot({path:'../qa/mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('UI checks passed');
}finally{await browser.close();await new Promise(r=>server.close(r));}
